### ISSUE TITLE
how to set value form function ?!

### ISSUE THREAD

**Issue by themesfa** [wilsonpinto/laravel-blade-directives#1]
hi . i want to set value like this:
`@set($setting, settings()->get($name) )`
but  as i see in code  you replace '(' and ')' with '' and function cant work!
any idea??

**Comment by wilsonpinto** [comment]
hi @themesfa,

its true, currently its not possible doing that. I will try to fix it soon as possible, however you are welcome to create a pull request if you find a solution for it.

**Comment by themesfa** [comment]
i found a solution and create a pr . please check it
